-- This script creates the table for storing calculated features.

CREATE TABLE IF NOT EXISTS feature_data (
    ts TIMESTAMP,
    symbol SYMBOL,
    rsi DOUBLE,
    macd DOUBLE,
    macd_signal DOUBLE
) timestamp(ts) PARTITION BY DAY;

-- This table will store the technical indicators generated by the
-- feature_engineering service.
-- It is partitioned by day for efficient time-series queries.
