selection:
  mode: manual  # or 'autonomous'
  symbols:
    - BTCUSDT
    - ETHUSDT
  frequencies:
    - 1m
    - 5m
  instruments:
    - spot
    - futures
autonomous:
  enabled: false
  method: bandit
  parameters:
    window_size: 30  # periods for volatility calculation
    exploration_rate: 0.1  # epsilon for bandit algorithm
    volatility_threshold: 0.05  # min volatility for selection
redis:
  host: localhost
  port: 6379
  db: 0
