# This file configures the asset selection for the data ingestion service.

messaging:
  broker: kafka # can be 'kafka', 'redis', or 'both'

selection:
  # 'manual' mode uses the explicit portfolios defined below.
  # 'autonomous' mode will select assets based on market conditions.
  mode: manual

# A list of portfolios, where each portfolio is tied to a specific exchange.
portfolios:
  - exchange: binance
    instruments:
      - spot
      - futures
    symbols:
      - BTCUSDT
      - ETHUSDT
    frequencies:
      - 1m
      - 5m

  - exchange: coinbase
    instruments:
      - spot
    symbols:
      - BTC-USD # Note the different symbol format for Coinbase
    frequencies:
      - 1m

autonomous:
  enabled: false
  method: bandit
  parameters:
    window_size: 30  # periods for volatility calculation
    exploration_rate: 0.1  # epsilon for bandit algorithm
    volatility_threshold: 0.05  # min volatility for selection
    max_selected_symbols: 5 # max number of symbols to select

redis:
  host: localhost
  port: 6379
  db: 0
  price_cache_size: 1000 # The number of recent prices to store for volatility calculation
